name : Deploy Lambda Function

on:
  push:  
   branches: [main]
jobs:
  deploy:
    runs-on : ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install zip tool
        uses: montudor/action-zip@v1
      - name: Create zip file for lambda Function
        run: zip -r code.zip .
      - name: AWS CLI v2
        uses: imhedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
            --function-name arn:aws:lambda:us-west-2:034298214272:function:TestCICDFunction \
            --zip-file fileb://code.zip"
        